# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    api_key: "STEAMAPIKEY"
    login_route: 'tasks_list'
    login_redirect: 'tasks_list'
    user_class: App\Entity\User
